CREATE SCHEMA IF NOT EXISTS carservice;
SET search_path TO carservice, public;

CREATE TABLE IF NOT EXISTS carservice.brand
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS carservice.type
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS carservice.model
(
    ID   TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    YEAR INTEGER NOT NULL,
    BRAND_ID BIGINT,
    UNIQUE (NAME, YEAR, BRAND_ID),
    CONSTRAINT BRAND_ID_FK FOREIGN KEY (BRAND_ID) REFERENCES carservice.brand (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS carservice.model_type
(
    MODEL_ID TEXT,
    TYPE_ID BIGINT,
    CONSTRAINT MODEL_ID_FK FOREIGN KEY (MODEL_ID) REFERENCES carservice.model (ID) ON DELETE CASCADE,
    CONSTRAINT TYPE_ID_FK FOREIGN KEY (TYPE_ID) REFERENCES carservice.type (ID) ON DELETE CASCADE
);